INSERT INTO STUDENT_TABLE (STUDENT_ID,COUNTRY,DEPARTMENT,S_NAME) VALUES (1,'country1','dept1','student1');
INSERT INTO STUDENT_TABLE (STUDENT_ID,COUNTRY,DEPARTMENT,S_NAME) VALUES (2,'country2','dept2','student2');
INSERT INTO STUDENT_TABLE (STUDENT_ID,COUNTRY,DEPARTMENT,S_NAME) VALUES (3,'country3','dept3','student3');
INSERT INTO STUDENT_TABLE (STUDENT_ID,COUNTRY,DEPARTMENT,S_NAME) VALUES (4,'country4','dept4','student4');
INSERT INTO STUDENT_TABLE (STUDENT_ID,COUNTRY,DEPARTMENT,S_NAME) VALUES (5,'country5','dept5','student5');
INSERT INTO STUDENT_TABLE (STUDENT_ID,COUNTRY,DEPARTMENT,S_NAME) VALUES (6,'country6','dept6','student6');

INSERT INTO USER_TABLE (USER_ID,PASSWORD,USERNAME) VALUES (1,'$2a$12$U4ifUs0CZzDBpOrGMH5P5.XrQR543/v6/a7uznbiWLInLVSqy4a2O','one');
INSERT INTO USER_TABLE (USER_ID,PASSWORD,USERNAME) VALUES (2,'$2a$12$YBPDEp0VgC2fqPV3yFaAw.x4I8hF5sJpM9gSktJOVRJ1G/GIwTYam','two');

INSERT INTO ROLE_TABLE (ROLE_ID,ROLENAME) VALUES (1,'ADMIN');
INSERT INTO ROLE_TABLE (ROLE_ID,ROLENAME) VALUES (2,'USER');

INSERT INTO USERS_ROLES (USER_ID,ROLE_ID) VALUES (1,1);
INSERT INTO USERS_ROLES (USER_ID,ROLE_ID) VALUES (2,2);